apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace}}
  labels:
    app: {{ .Values.deployment.app}}
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app:  {{ .Values.deployment.app}}
  template:
    metadata:
      labels:
        app:  {{ .Values.deployment.app}}
    spec:
      containers:
        - name:  {{ .Values.deployment.app}}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort:  {{ .Values.image.containerPort}}
       