deployment:
  name: react-deployment
  app:  my-react-app

namespace: react
replicas: 1

image:
  name: kejsiblushi/project_img
  tag: latest
  imagePullPolicy: IfNotPresent
  containerPort: 80

service:
  name: react-service
  protocol: TCP
  port: 80
  targetPort: 80
